version: '3'
services:
  postgres:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"


  app:
    build: .
    env_file:
      - .env
    ports:
      - "80:8000"
    depends_on:
      - postgres