version: "3.9"
services:
  python-app:
    build:
      dockerfile: Dockerfile
    ports:
      - "80:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_BD: my_ptgr
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd12345